### ISSUE TITLE
Convergence des documentations

### ISSUE THREAD

**Issue by jdesboeufs** [sgmap/apicarto#10]
Nous sommes tombés d'accord pour faire converger les différentes documentations vers Swagger.

État des lieux des documentations :
* Quartiers prioritaires : `API.md`
* Appellations viticoles : non documenté car non stabilisé
* Cadastre : Swagger
* Codes postaux : non documenté

L'infrastructure en elle-même n'existe pas, la documentation n'est pas consultable facilement, sauf pour `API.md`.

Les API devraient aussi converger entre elles.

Bref le sujet est à prendre, de préférence pour avoir quelque chose d'ici le 10/12/2015.

Toutes les bonnes volontés sont les bienvenues sur ce sujet ;)
cc @vinsag @mborne @noirbizarre @MattiSG

**Comment by vinsag** [comment]
Est ce qu'une documentation a déja été commencé ? Pour Appelations viticoles, il faut en faire une sur la base de l'existant ou nous attendons la stabilisation.

**Comment by jdesboeufs** [comment]
Non page blanche pour le moment.
Si on attend la stabilisation, on risque d'attendre longtemps car en ce qui me concerne j'ai très peu de temps disponible jusqu'à janvier !

**Comment by vinsag** [comment]
Concernant la documentation cadastre avec swagger UI , j'ai pu générer un serveur pour nodejs  sur mon fichier: http://editor.swagger.io/#/
Ce qui m'a permis en lancer node index de pouvoir visualiser mon fichier swagger en ligne sur l'interfarce UI
Par contre au lancement j'avais des erreurs, j'avais quelques erreurs sur le fichier qui marche bien avec Swagger Editor sur des tableaux. J'ai supprimé des lignes mais je vais essayer de voir comment nous pouvons corriger ce point.
