### ISSUE TITLE
Erreur avec ` dans le code communes aoc

### ISSUE THREAD

**Issue by vinsag** [sgmap/apicarto#12]
Lorsque je veux faire un npm start avec les paramètres du geoportail, je me retrouve avec des erreurs à cause  du ` : /home/vsagniez/node_project/apicarto/helpers/communes.js:9
                return format(`
                              ^
SyntaxError: Unexpected token ILLEGAL

**Comment by jdesboeufs** [comment]
Je ne comprends pas.
Peux-tu me fournir un exemple ?

**Comment by jdesboeufs** [comment]
Ah c'est bon je sais. Tu as une vieille version de Node.js, surement la 0.12.
Il te faut la version 4.0 minimum, et je te recommande la 4.2.

Je te suggère d'utiliser [nvm](https://github.com/creationix/nvm) pour gérer tes versions de Node.js.

**Comment by vinsag** [comment]
Lorque que je lance un npm start avec tous les modules que j'ai activé, il bloque sur commune :+1: 
apicarto/helpers/communes.js:9
                return format(`
                              ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/node_project/apicarto/server.js:8:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 8

J'ai exactement la même chose pour aoc si je mets en commentaires la ligne : var communesHelper = require('./helpers/communes'); dans server.js
apicarto/controllers/aoc.js:5
var inQuery = Handlebars.compile(`
                                 ^
SyntaxError: Unexpected token ILLEGAL

Ca me fait la même erreur sur quartiers prioritaires, si  je mets en commentaire le require pour aoc et commune:
apicarto/controllers/quartiers-prioritaires.js:10
    req.pgClient.query(format(`
                              ^
SyntaxError: Unexpected token ILLEGAL

**Comment by jdesboeufs** [comment]
J'ai répondu juste au dessus.
Ta version de Node.js ne comprend pas les Template Strings d'ES6.
