### ISSUE TITLE
Retour incorrect lors du chargement du cadastre à partir d'une géométrie

### ISSUE THREAD

**Issue by jdesboeufs** [sgmap/apicarto#19]
Xavier qui bosse sur __TéléProcédureSimplifié__ m'a signalé une anomalie.

Lorsqu'il effectue une requête `POST` sur `/cadastre/geometrie` avec ce contenu :

```json
{
	"geom": {
		"type": "Feature",
		"geometry": {
			"type": "Polygon",
			"coordinates": [
				[
					[5.93536376953125, 48.91888968903368],
					[5.93536376953125, 49.26780455063753],
					[7.094421386718749, 49.26780455063753],
					[7.094421386718749, 48.91888968903368],
					[5.93536376953125, 48.91888968903368]
				]
			]
		}
	}
}
```

Il obtient `null` au lieu d'une `FeatureCollection`, et à défaut d'une erreur.

À ajouter dans les tests et à investiguer.

cc @vinsag @mborne

**Comment by vinsag** [comment]
Ou se trouve cette géométrie car je ne l'ai pas en france mais en afrique ? :(. Par contre je suis d'accord de mieux gérer les erreurs qui sont envoyés par le flux wfs et avoir un message d' erreur plus approprié.

**Comment by jdesboeufs** [comment]
Elle est censée être en Lorraine, mais peut-être qu'il y a une inversion de coordonnées quelque part.
On regarde ça semaine prochaine !
